# -*- coding: utf-8 -*-
"""Bibek_Gyawali_2409003.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUFfrhmiFigmKU-wf0VvlTFIPK4ZKgP1
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Assignment1

ls

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Tasks - To - Do:
#3.1 Problem - 1: Getting Started with Data Exploration

#reading the csv file
df = pd.read_csv("WHR-2024-5CS037.csv")

#Data Exploration and Understanding:

#Dataset Overview:

# 1. Load the dataset and display the first 10 rows.
print("First 10 rows of the dataset:")
print(df.head(10))

# 2. Identify the number of rows and columns in the dataset.
print("\nDataset Shape (Rows, Columns):", df.shape)

# 3. List all the columns and their data types
print("\nColumns and Data Types:")
print(df.dtypes)

# Basic Statistics

#1. Calculate the mean, median, and standard deviation for the Score column.
mean_score = df['score'].mean()
median_score = df['score'].median()
std_score = df['score'].std()

print(f"\nMean Happiness Score: {mean_score}")
print(f"Median Happiness Score: {median_score}")
print(f"Standard Deviation of Happiness Score: {std_score}")

#2. Identify the country with the highest and lowest happiness scores.
max_score_country = df[df['score'] == df['score'].max()]['Country name'].iloc[0]
min_score_country = df[df['score'] == df['score'].min()]['Country name'].iloc[0]

print(f"\nCountry with the Highest Happiness Score: {max_score_country}")
print(f"Country with the Lowest Happiness Score: {min_score_country}")

#Missign values

# 1. Check if there are any missing values in the dataset. If so, display the total count for each column.
print("\nMissing Values in Each Column:")
print(df.isnull().sum())

#Filtering and Sorting

# 1. Filter the dataset to show only the countries with a Score greater than 7.5.
filtered_df = df[df['score'] > 7.5]

# 2. For the filtered dataset - Sort the dataset by GDP per Capita in descending order and display the top 10 rows.
sorted_df = filtered_df.sort_values(by='Log GDP per capita', ascending=False).head(10)
print("\nTop 10 Countries with Score > 7.5 Sorted by GDP per Capita:")
print(sorted_df)

# Add new columns 'Happiness_Category'
conditions = [
    df['score'] < 4,
    (df['score'] >= 4) & (df['score'] <= 6),
    df['score'] > 6
]
categories = ['Low', 'Medium', 'High']

df['Happiness_Category'] = pd.cut(df['score'], bins=[-float('inf'), 4, 6, float('inf')], labels=categories)
print("\nDataset with 'Happiness_Category' column added:")
print(df.head(10))
df.to_csv('WHR-2024-5CS037.csv', index=False)

#Data Visualizations

# 1. Bar Plot: Top 10 Happiest Countries by Score
top_10_happiest = df.nlargest(10, 'score')  # Select the top 10 countries by score
plt.figure(figsize=(10, 6))
sns.barplot(x='score', y='Country name', data=top_10_happiest)
plt.title('Top 10 Happiest Countries by Score')
plt.xlabel('Happiness Score')
plt.ylabel('Country')
plt.show()

# 2. Line Plot: Top 10 Unhappiest Countries by Score
top_10_unhappiest = df.nsmallest(10, 'score')  # Select the bottom 10 countries by score
plt.figure(figsize=(10, 6))
plt.plot(top_10_unhappiest['Country name'], top_10_unhappiest['score'], marker='o', linestyle='-', color='red')
plt.title('Top 10 Unhappiest Countries by Score')
plt.xlabel('Country')
plt.ylabel('Happiness Score')
plt.xticks(rotation=45)  # Rotate country names for better visibility
plt.show()

# 3. Histogram: Distribution of Happiness Scores
plt.figure(figsize=(8, 5))
sns.histplot(df['score'], bins=20, kde=True, color='blue')
plt.title('Distribution of Happiness Scores')
plt.xlabel('Happiness Score')
plt.ylabel('Frequency')
plt.show()

# 4. Scatter Plot: GDP per Capita vs Happiness Score
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Log GDP per capita', y='score', data=df, color='blue', s=100)
plt.title('Scatter Plot of GDP per Capita vs Happiness Score')
plt.xlabel('Log GDP per Capita')
plt.ylabel('Happiness Score')
plt.show()

#3.2 Problem - 2 - Some Advance Data Exploration Task:

# Task - 1: Setup Task - Preparing the South-Asia

# 1. Define South Asian countries
south_asian_countries = ["Afghanistan", "Bangladesh", "Bhutan", "India",
                         "Maldives", "Nepal", "Pakistan", "Sri Lanka"]

# 2. Filter the dataset for South Asian countries
south_asia_df = df[df['Country name'].isin(south_asian_countries)]
print("\nSouth Asia Dataset:")
print(south_asia_df)

# 3. Save the filtered South Asia dataframe to a new CSV
south_asia_df.to_csv("South_Asia_Happiness.csv", index=False)

# Task - 2: Composite Score Ranking

# 1. Calculate Composite Score
south_asia_df['Composite Score'] = (0.40 * south_asia_df['Log GDP per capita'] +
                                    0.30 * south_asia_df['Social support'] +
                                    0.30 * south_asia_df['Healthy life expectancy'])

# 2. Rank the South Asian countries based on the Composite Score in descending order.
ranked_df = south_asia_df.sort_values(by='Composite Score', ascending=False)
print("\nSouth Asia Countries Ranked by Composite Score:")
print(ranked_df[['Country name', 'Composite Score']])

# 3. Visualize the top 5 countries using a horizontal bar chart showing the Composite Score.
plt.figure(figsize=(10, 6))
sns.barplot(x='Composite Score', y='Country name', data=ranked_df.head(5))
plt.title('Top 5 South Asian Countries by Composite Score')
plt.xlabel('Composite Score')
plt.ylabel('Country')
plt.show()

# 4. Discuss whether the rankings based on the Composite Score align with the original Score - support your discussion with some visualization plot.
plt.figure(figsize=(10, 6))
sns.scatterplot(x='score', y='Composite Score', data=ranked_df, hue='Country name', s=100, palette='tab10')
plt.title('Comparison of Happiness Score and Composite Score')
plt.xlabel('Original Happiness Score')
plt.ylabel('Composite Score')
plt.legend(title='Country')
plt.show()

# Task - 3: Outlier Detection

# 1. Identify outliers based on Happiness Score and GDP
Q1 = south_asia_df[['score', 'Log GDP per capita']].quantile(0.25)
Q3 = south_asia_df[['score', 'Log GDP per capita']].quantile(0.75)
IQR = Q3 - Q1

#2. Define outliers using 1.5 * IQR rule
outlier_condition = ((south_asia_df['score'] < (Q1['score'] - 1.5 * IQR['score'])) |
                     (south_asia_df['score'] > (Q3['score'] + 1.5 * IQR['score']))) | \
                    ((south_asia_df['Log GDP per capita'] < (Q1['Log GDP per capita'] - 1.5 * IQR['Log GDP per capita'])) |
                     (south_asia_df['Log GDP per capita'] > (Q3['Log GDP per capita'] + 1.5 * IQR['Log GDP per capita'])))

outliers = south_asia_df[outlier_condition]
print("\nOutliers in South Asia:")
print(outliers[['Country name', 'score', 'Log GDP per capita']])

# 3. Scatter plot highlighting outliers
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Log GDP per capita', y='score', data=south_asia_df, color='blue', label='Regular')
sns.scatterplot(x='Log GDP per capita', y='score', data=outliers, color='red', s=100, label='Outliers')
plt.title('Outlier Detection: GDP vs Happiness Score')
plt.xlabel('GDP')
plt.ylabel('Happiness Score')
plt.legend()
plt.show()

# Task - 4: Exploring Trends Across Metrics

# 1. Calculate correlations for two metrics with Happiness Score
metric_1 = 'Freedom to make life choices'
metric_2 = 'Generosity'

correlation_1 = south_asia_df['score'].corr(south_asia_df[metric_1])
correlation_2 = south_asia_df['score'].corr(south_asia_df[metric_2])

print(f"\nCorrelation between Happiness Score and {metric_1}: {correlation_1:.2f}")
print(f"Correlation between Happiness Score and {metric_2}: {correlation_2:.2f}")

# 2. Scatter plots with trendlines
plt.figure(figsize=(10, 5))
sns.regplot(x=metric_1, y='score', data=south_asia_df, color='blue')
plt.title(f'Scatter Plot of {metric_1} vs score')
plt.xlabel(metric_1)
plt.ylabel('score')
plt.show()

plt.figure(figsize=(10, 5))
sns.regplot(x=metric_2, y='score', data=south_asia_df, color='purple')
plt.title(f'Scatter Plot of {metric_2} vs Happiness Score')
plt.xlabel(metric_2)
plt.ylabel('Happiness Score')
plt.show()

# Task - 5: Gap Analysis

# 1. Add GDP-Score Gap column
south_asia_df['GDP-Score Gap'] = south_asia_df['Log GDP per capita'] - south_asia_df['score']

# 2. Rank countries by GDP-Score Gap (ascending and descending)
gap_ascending = south_asia_df.sort_values(by='GDP-Score Gap', ascending=True)
gap_descending = south_asia_df.sort_values(by='GDP-Score Gap', ascending=False)

# Largest Positive GDP-Score Gap:
print("\nTop 3 Countries with Largest Positive GDP-Score Gap:")
print(gap_descending.head(3)[['Country name', 'GDP-Score Gap']])

# Largest Negative GDP-Score Gap:
print("\nTop 3 Countries with Largest Negative GDP-Score Gap:")
print(gap_ascending.head(3)[['Country name', 'GDP-Score Gap']])

# 3. Visualize top 3 countries for both positive and negative gaps
plt.figure(figsize=(10, 6))
sns.barplot(x='GDP-Score Gap', y='Country name', data=gap_descending.head(3), color='blue', label='Positive Gap')
sns.barplot(x='GDP-Score Gap', y='Country name', data=gap_ascending.head(3), color='purple', label='Negative Gap')
plt.title('Top 3 Countries with Positive and Negative GDP-Score Gaps')
plt.xlabel('GDP-Score Gap')
plt.ylabel('Country')
plt.legend()
plt.show()

#3.3 Problem - 3 - Comparative Analysis:

#Task - 1 - Setup Task - Preparing the Middle Eastern Dataset:

#Tasks:

#1. Similar in Task - 1 of Problem 2 create a dataframe from middle eastern countries. For hint use the
#following list:
middle_east_countries = ["Bahrain", "Iran", "Iraq", "Israel", "Jordan",
                         "Kuwait", "Lebanon", "Oman", "Palestine", "Qatar",
                         "Saudi Arabia", "Syria", "United Arab Emirates", "Yemen"]

middle_east_df = df[df['Country name'].isin(middle_east_countries)]
print("\nMiddle East Dataset:")
print(middle_east_df)

# 1. Descriptive Statistics:

# Calculate mean and standard deviation of Score for South Asia and Middle East
print("\nDescriptive Statistics:")

print(f"South Asia Mean Happiness Score: {south_asia_df['score'].mean():.2f}")
print(f"Middle East Mean Happiness Score: {middle_east_df['score'].mean():.2f}")

print(f"South Asia Standard Deviation: {south_asia_df['score'].std():.2f}")
print(f"Middle East Standard Deviation: {middle_east_df['score'].std():.2f}")

# Determine which region has a higher average happiness score
higher_region = "South Asia" if south_asia_df['score'].mean() > middle_east_df['score'].mean() else "Middle East"
print(f"\nRegion with Higher Average Happiness Score: {higher_region}")

# 2. Top and Bottom Performers:

# Identify top 3 and bottom 3 countries based on score for each region
print("\nTop and Bottom Performers:")

print("Top 3 South Asian Countries:")
print(south_asia_df.nlargest(3, 'score')[['Country name', 'score']])

print("\nBottom 3 South Asian Countries:")
print(south_asia_df.nsmallest(3, 'score')[['Country name', 'score']])

print("\nTop 3 Middle Eastern Countries:")
print(middle_east_df.nlargest(3, 'score')[['Country name', 'score']])

print("\nBottom 3 Middle Eastern Countries:")
print(middle_east_df.nsmallest(3, 'score')[['Country name', 'score']])

# Plot bar charts for top and bottom performers
# Plot Top 3 South Asian Countries
plt.figure(figsize=(10, 6))
sns.barplot(x='score', y='Country name', data=south_asia_df.nlargest(3, 'score'))
plt.title('Top 3 South Asian Countries by Happiness Score')
plt.show()

# Plot Bottom 3 South Asian Countries
plt.figure(figsize=(10, 6))
sns.barplot(x='score', y='Country name', data=south_asia_df.nsmallest(3, 'score'))
plt.title('Bottom 3 South Asian Countries by Happiness Score')
plt.show()

# Plot Top 3 Middle Eastern Countries
plt.figure(figsize=(10, 6))
sns.barplot(x='score', y='Country name', data=middle_east_df.nlargest(3, 'score'))
plt.title('Top 3 Middle Eastern Countries by Happiness Score')
plt.show()

# Plot Bottom 3 Middle Eastern Countries
plt.figure(figsize=(10, 6))
sns.barplot(x='score', y='Country name', data=middle_east_df.nsmallest(3, 'score'))
plt.title('Bottom 3 Middle Eastern Countries by Happiness Score')
plt.show()

# 3. Metric Comparisons:

# Compare GDP per Capita, Social Support, and Healthy Life Expectancy

metrics = ['Log GDP per capita', 'Social support', 'Healthy life expectancy']

plt.figure(figsize=(12, 6))
for i, metric in enumerate(metrics):
    plt.subplot(1, 3, i+1)
    sns.barplot(x='Region', y=metric, data=pd.concat([
        south_asia_df.assign(Region='South Asia'),
        middle_east_df.assign(Region='Middle East')
    ]))
    plt.title(metric)

plt.tight_layout()
plt.show()

#Which metrics show the largest disparity between the two regions?

# 4. Happiness Disparity:

# Compute range and coefficient of variation (CV) for Score
def compute_stats(df, region_name):
    score_range = df['score'].max() - df['score'].min()
    score_cv = (df['score'].std() / df['score'].mean()) * 100
    print(f"\n{region_name} Happiness Score Range: {score_range:.2f}")
    print(f"{region_name} Happiness Score Coefficient of Variation: {score_cv:.2f}%")

compute_stats(south_asia_df, "South Asia")
compute_stats(middle_east_df, "Middle East")

# 5. Correlation Analysis:

# Correlation of Score with Freedom and Generosity
metrics_to_correlate = ['Freedom to make life choices', 'Generosity']

print("\nCorrelation Analysis:")
for metric in metrics_to_correlate:
    south_corr = south_asia_df['score'].corr(south_asia_df[metric])
    middle_corr = middle_east_df['score'].corr(middle_east_df[metric])
    print(f"Correlation of Score with {metric} in South Asia: {south_corr:.2f}")
    print(f"Correlation of Score with {metric} in Middle East: {middle_corr:.2f}")

# Scatter plot for correlation visualization with Freedom
plt.figure(figsize=(10, 5))
sns.regplot(x='Freedom to make life choices', y='score', data=south_asia_df, label='South Asia', color='blue')
sns.regplot(x='Freedom to make life choices', y='score', data=middle_east_df, label='Middle East', color='orange')
plt.title("Freedom to Make Life Choices vs Happiness Score")
plt.legend()
plt.show()

# Scatter plot for correlation visualization with Generosity
plt.figure(figsize=(10, 5))
sns.regplot(x='Generosity', y='score', data=south_asia_df, label='South Asia', color='blue')
sns.regplot(x='Generosity', y='score', data=middle_east_df, label='Middle East', color='orange')
plt.title("Generosity vs Happiness Score")
plt.legend()
plt.show()

# 6. Outlier Detection:

# Detect outliers in Score and GDP per Capita using IQR
def detect_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[column] < Q1 - 1.5 * IQR) | (df[column] > Q3 + 1.5 * IQR)]
    return outliers

outliers_south = detect_outliers(south_asia_df, 'score')
outliers_middle = detect_outliers(middle_east_df, 'score')

print("\nOutliers in South Asia based on Score:")
print(outliers_south[['Country name', 'score']])

print("\nOutliers in Middle East based on Score:")
print(outliers_middle[['Country name', 'score']])

# 3. Scatter plot highlighting outliers
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Log GDP per capita', y='score', data=south_asia_df, color='blue', label='Regular')
sns.scatterplot(x='Log GDP per capita', y='score', data=outliers, color='red', s=100, label='Outliers')
plt.title('Outlier Detection: GDP vs Happiness Score')
plt.xlabel('GDP')
plt.ylabel('Happiness Score')
plt.legend()
plt.show()


# Scatter Plot for Middle East highlighting outliers
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Log GDP per capita', y='score', data=middle_east_df, color='green', label='Regular')
sns.scatterplot(x='Log GDP per capita', y='score', data=outliers_middle, color='red', s=100, label='Outliers')
plt.title('Outlier Detection in Middle East: GDP vs Happiness Score')
plt.xlabel('Log GDP per capita')
plt.ylabel('Happiness Score')
plt.legend()
plt.show()

# 7. Visualization: Boxplots
plt.figure(figsize=(10, 6))
sns.boxplot(x='Region', y='score', data=pd.concat([
    south_asia_df.assign(Region='South Asia'),
    middle_east_df.assign(Region='Middle East')
]))
plt.title("Comparison of Happiness Score Distribution: South Asia vs Middle East")
plt.show()

